/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";

export const OAuthConfigurationIF = t.iface([], {
  clientId: "string",
  resource: "string",
  oAuthUri: "string",
  tokenUri: "string",
  adminClaimName: "string",
  scope: "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  OAuthConfigurationIF,
};
export default exportedTypeSuite;
